// lib/productos.ts
import type { Producto } from "./tipos";

export const PRODUCTOS: Producto[] = [
  {
    slug: "corte-dama",
    nombre: "Corte de dama",
    categoria: "Cortes, color y peinado",
    imagen: undefined,
    paraQuien: "Para la que quiere un corte que le acomode a su cara y a su día a día.",
    beneficio: "Sales con un corte hecho a tu medida y el cabello listo para lucir.",
    caracteristicas: ["Incluye diagnóstico y lavado", "De 45 a 75 minutos", "El precio depende del largo y el acabado"],
    precio: "Desde $250",
    destacado: true,
  },
  {
    slug: "corte-caballero",
    nombre: "Corte de caballero",
    categoria: "Cortes, color y peinado",
    imagen: undefined,
    paraQuien: "Para el que quiere un corte bien hecho y salir arreglado sin batallar.",
    beneficio: "Te vas con el corte definido y, si quieres, la barba en su punto.",
    caracteristicas: ["Incluye lavado rápido y fijación", "Diseño con navaja o arreglo de barba", "De 30 a 60 minutos"],
    precio: "Desde $150",
  },
  {
    slug: "efectos-color",
    nombre: "Efectos de color",
    categoria: "Cortes, color y peinado",
    imagen: undefined,
    paraQuien: "Para la que quiere aclarar o darle dimensión al cabello, tipo balayage, luces o mechas.",
    beneficio: "Consigues un color con el matiz cuidado y un acabado natural.",
    caracteristicas: ["Incluye valoración previa y matizador", "El precio depende del largo y el nivel de aclarado", "De 3 a 5.5 horas"],
    precio: "Desde $1,200",
  },
  {
    slug: "alaciados-keratinas",
    nombre: "Alaciados y keratinas",
    categoria: "Cortes, color y peinado",
    imagen: undefined,
    paraQuien: "Para la que trae el cabello encrespado o rebelde y lo quiere manejable y con brillo.",
    beneficio: "Dejas el cabello más lacio, suave y fácil de peinar por semanas.",
    caracteristicas: ["Incluye sellado térmico mechón por mechón", "El precio depende del largo y el volumen", "De 2.5 a 4.5 horas"],
    precio: "Desde $800",
  },
  {
    slug: "peinados",
    nombre: "Peinados",
    categoria: "Cortes, color y peinado",
    imagen: undefined,
    paraQuien: "Para la que tiene un evento y quiere un peinado que aguante toda la noche.",
    beneficio: "Llegas peinada y con la fijación lista para que dure hasta el final.",
    caracteristicas: ["Ondas sueltas o recogido elaborado", "Mejor llegar con el cabello limpio y seco", "De 45 a 90 minutos"],
    precio: "Desde $350",
  },
  {
    slug: "permanente",
    nombre: "Permanente",
    categoria: "Cortes, color y peinado",
    imagen: undefined,
    paraQuien: "Para la que quiere rizos u ondas que le duren y peinarse en menos tiempo.",
    beneficio: "Sales con el rizo marcado y un cabello con más cuerpo y movimiento.",
    caracteristicas: ["Rizo u onda, según lo que busques", "Da cuerpo y movimiento al cabello", "Pregúntanos precio y duración"],
    precio: "Pregúntanos",
  },
  {
    slug: "corte-ninos",
    nombre: "Corte de niño y niña",
    categoria: "Cortes, color y peinado",
    imagen: undefined,
    paraQuien: "Para los más peques, con paciencia y un corte a su medida.",
    beneficio: "Tu hij@ sale bien peinad@ y sin pasarla mal en la silla.",
    caracteristicas: ["Para niñas y niños", "Trato paciente y rápido", "Pregúntanos el precio"],
    precio: "Pregúntanos",
  },
  {
    slug: "botox-capilar",
    nombre: "Botox capilar",
    categoria: "Tratamientos capilares",
    imagen: undefined,
    paraQuien: "Para la que trae el cabello dañado o sin vida y lo quiere sentir nutrido y con cuerpo.",
    beneficio: "Recuperas suavidad y brillo en el cabello.",
    caracteristicas: ["Hidrata a fondo y baja el frizz", "No es alaciado, es tratamiento", "De 1.5 a 2.5 horas"],
    precio: "Desde $600",
    destacado: true,
  },
  {
    slug: "nanoplastia",
    nombre: "Nanoplastia",
    categoria: "Tratamientos capilares",
    imagen: undefined,
    paraQuien: "Para la que quiere alisar el cabello y bajarle el frizz.",
    beneficio: "Dejas el cabello más lacio y con menos frizz.",
    caracteristicas: ["Alaciado orgánico, libre de formol", "El precio depende del largo", "De 3 a 5 horas"],
    precio: "Desde $900",
  },
  {
    slug: "cirugia-capilar",
    nombre: "Cirugía capilar",
    categoria: "Tratamientos capilares",
    imagen: undefined,
    paraQuien: "Para la que trae el cabello muy maltratado y quiere reconstruirlo a fondo.",
    beneficio: "Reconstruyes la fibra y recuperas un cabello más fuerte y manejable.",
    caracteristicas: ["Reconstrucción intensiva para cabello procesado", "Deja un efecto liso medio", "De 2 a 3.5 horas"],
    precio: "Desde $800",
  },
  {
    slug: "limpieza-puntas",
    nombre: "Limpieza de puntas",
    categoria: "Tratamientos capilares",
    imagen: undefined,
    paraQuien: "Para la que quiere quitar las puntas maltratadas sin perder el largo.",
    beneficio: "Te quitas el maltrato de las puntas y el cabello se ve más sano.",
    caracteristicas: ["Retira la orzuela sin perder largo", "Con tijera o pulidora", "De 30 a 45 minutos"],
    precio: "Desde $150",
  },
  {
    slug: "planchado-cejas",
    nombre: "Planchado de cejas",
    categoria: "Cejas, pestañas y maquillaje",
    imagen: undefined,
    paraQuien: "Para la que quiere las cejas peinadas hacia arriba y con forma.",
    beneficio: "Dejas las cejas alineadas y con una forma más definida por semanas.",
    caracteristicas: ["Incluye depilación con cera o hilo", "Ordena y da forma a la ceja", "De 45 a 60 minutos"],
    precio: "Desde $250",
  },
  {
    slug: "microblading",
    nombre: "Microblading",
    categoria: "Cejas, pestañas y maquillaje",
    imagen: undefined,
    paraQuien: "Para la que tiene poco vello en las cejas y quiere pelo a pelo con aspecto natural.",
    beneficio: "Recuperas cejas pobladas con trazos que imitan el vello real.",
    caracteristicas: ["Técnica pelo a pelo", "Incluye visagismo y prueba de tono", "De 2 a 3 horas"],
    precio: "Desde $1,500",
  },
  {
    slug: "microshading",
    nombre: "Microshading",
    categoria: "Cejas, pestañas y maquillaje",
    imagen: undefined,
    paraQuien: "Para la que quiere las cejas con efecto sombreado, tipo maquillaje, más suave que el pelo a pelo.",
    beneficio: "Consigues cejas con efecto difuminado que se ve como maquillaje bien puesto.",
    caracteristicas: ["Efecto sombreado o degradado", "Ideal para piel mixta o grasa", "De 2 a 3.5 horas"],
    precio: "Desde $1,600",
  },
  {
    slug: "aplicacion-pestanas",
    nombre: "Aplicación de pestañas",
    categoria: "Cejas, pestañas y maquillaje",
    imagen: undefined,
    paraQuien: "Para la que quiere pestañas largas y con volumen sin depender del rímel.",
    beneficio: "Te levantas con la mirada lista, sin tener que maquillar las pestañas.",
    caracteristicas: ["Clásicas, híbridas o volumen ruso", "Retoque desde $250", "De 1.5 a 2.5 horas"],
    precio: "Desde $450",
    destacado: true,
  },
  {
    slug: "lash-lifting",
    nombre: "Lash lifting",
    categoria: "Cejas, pestañas y maquillaje",
    imagen: undefined,
    paraQuien: "Para la que quiere curvar y levantar sus propias pestañas sin extensiones.",
    beneficio: "Realzas tus pestañas naturales con más curva y sin usar postizos.",
    caracteristicas: ["Levanta y curva tu pestaña natural", "Incluye tinte y sellado de keratina", "De 45 a 75 minutos"],
    precio: "Desde $250",
  },
  {
    slug: "maquillaje",
    nombre: "Maquillaje",
    categoria: "Cejas, pestañas y maquillaje",
    imagen: undefined,
    paraQuien: "Para la que tiene un evento y quiere un maquillaje que le dure y se vea natural.",
    beneficio: "Llegas maquillada y lista, con un acabado que aguanta toda la ocasión.",
    caracteristicas: ["Para eventos y ocasiones especiales", "A tu estilo, natural o más marcado", "Pregúntanos precio y disponibilidad"],
    precio: "Pregúntanos",
  },
];

/** Productos de una categoría, con el destacado primero. */
export function productosPorCategoria(categoria: string): Producto[] {
  return PRODUCTOS.filter((p) => p.categoria === categoria).sort(
    (a, b) => Number(b.destacado ?? false) - Number(a.destacado ?? false)
  );
}

/** Busca un producto por su slug (para la ficha individual). */
export function productoPorSlug(slug: string): Producto | undefined {
  return PRODUCTOS.find((p) => p.slug === slug);
}
